### PR TITLE
Added fix for deleting symlinks in TestDrive

### PR DESCRIPTION
**Pull request by mikeclayton**
see https://github.com/pester/Pester/issues/1100

### CODE REVIEW

**Comment by nohwnd** [comment]
@mikeclayton from the test results it seems that the `-Attributes` parameter is present only on PowerShell 5 and latest.

**Comment by mikeclayton** [comment]
@nohwnd - Ah, not so good :-(. I saw the link to the broken build, but didn't think to click "Log in as guest" to see the build log!

I've changed it to use what I think are 2.0-compatible parameters - I'll check if the build works this time.

I also added ```-Recurse``` as it would only remove symlinks from the root of Testdrive:\ otherwise. I guess this could *potentially* cause a performance issue if tests create a lot of files and folders, but ```Clear-TestDrive``` already does this so hopefully that's not a major concern.

**Comment by nohwnd** [comment]
@mikeclayton the previous issue was resolved, but still some remain. Looks like PowerShell 5 is the only one supporting symlinks directly.

**Comment by mikeclayton** [comment]
@nohwnd - backward compatibility is hard :-S.

It looks like it's the setup in the test that's failing now - the old-school way of doing it seems to be to call "cmd /c mklink" according to https://stackoverflow.com/questions/894430/creating-hard-and-soft-links-using-powershell

Would that be an ok way to go, or is it likely to cause more problems that it solves?

(I'm not around for the next week, but I can pick this up again when I'm available again).

Cheers,

M

**Comment by nohwnd** [comment]
@mikeclayton I implemented the test in a way that it works on powershell 2 as well as 5. But the problem is that it needs admin rights to run, so I commented the test for now. Later I will move the tests and set them up to run as admin (which we already do on the build server because your tests have passed few times). No action needed I will merge as is.

**Pull request merged**
