### PR TITLE
Export functions from Environment.ps1 - Fix #830

### LINKED ISSUE #830: Functions from Environment.ps1 are not exported
I just found that functions
- GetPesterPsVersion
- GetPesterOs
- Get-TempDirectory
from the Functions\Environment.ps1 file are not exported by Pester module
- [in the manifest file](https://github.com/pester/Pester/blob/23eaf10c354eb4fbebc9d44f960bec89b24b5976/Pester.psd1#L28-L53)
- [in the block of exported module members](https://github.com/pester/Pester/blob/23eaf10c354eb4fbebc9d44f960bec89b24b5976/Pester.psm1#L1084-L1090)

Additionally, they are not advanced functions (lack of `[cmdletbindings()]`) so they need to be added to the list used by the [all non-deprecated, non-internal public commands use CmdletBinding' test](https://github.com/pester/Pester/blob/23eaf10c354eb4fbebc9d44f960bec89b24b5976/Pester.Tests.ps1#L129-L133).

I think that this need to be corrected before releasing Pester v4.0 because if it will not be correct we will deliver "orphaned" functions.

### PR DESCRIPTION
**Pull request by it-praktyk**

### CODE REVIEW

**Comment by vors** [comment]
On macOS with powershell 6.0.0-beta.5 I got these errors

```
    Context exception thrown in nested functions in file
      [+] produces correct message lines. 53ms
      [-] produces correct trace lines. 45ms
        Expected: {True}
        But was:  {False}
        236:                         Should be $true
        at Invoke-LegacyAssertion, /Users/vors/dev/Pester/Functions/Assertions/Should.ps1: line 190
        at Should<End>, /Users/vors/dev/Pester/Functions/Assertions/Should.ps1: line 133
        at <ScriptBlock>, /Users/vors/dev/Pester/Functions/Output.Tests.ps1: line 235
        at Invoke-Test, /Users/vors/dev/Pester/Functions/It.ps1: line 258
        at ItImpl, /Users/vors/dev/Pester/Functions/It.ps1: line 207
        at It, /Users/vors/dev/Pester/Functions/It.ps1: line 121
        at <ScriptBlock>, /Users/vors/dev/Pester/Functions/Output.Tests.ps1: line 231
        at DescribeImpl, /Users/vors/dev/Pester/Functions/Describe.ps1: line 161
        at Describe, /Users/vors/dev/Pester/Functions/Describe.ps1: line 86
        at Context, /Users/vors/dev/Pester/Functions/Context.ps1: line 60
        at <ScriptBlock>, /Users/vors/dev/Pester/Functions/Output.Tests.ps1: line 211
        at DescribeImpl, /Users/vors/dev/Pester/Functions/Describe.ps1: line 161
        at Describe, /Users/vors/dev/Pester/Functions/Describe.ps1: line 86
        at <ScriptBlock>, /Users/vors/dev/Pester/Functions/Output.Tests.ps1: line 152
        at InModuleScope, /Users/vors/dev/Pester/Functions/InModuleScope.ps1: line 84
        at <ScriptBlock>, /Users/vors/dev/Pester/Functions/Output.Tests.ps1: line 120
        at <ScriptBlock>, /Users/vors/dev/Pester/Pester.psm1: line 792
        at Invoke-Pester<End>, /Users/vors/dev/Pester/Pester.psm1: line 807
        at <ScriptBlock>, <No file>: line 1

    Context nested exceptions thrown in file
      [+] produces correct message lines. 97ms                                                                                 [-] produces correct trace line. 41ms                                                                                      Expected: {3}                                                                                                            But was:  {14}                                                                                                   
        280:                     $r.Trace.Count | Should be 3
        at Invoke-LegacyAssertion, /Users/vors/dev/Pester/Functions/Assertions/Should.ps1: line 190
        at Should<End>, /Users/vors/dev/Pester/Functions/Assertions/Should.ps1: line 133
        at <ScriptBlock>, /Users/vors/dev/Pester/Functions/Output.Tests.ps1: line 280
        at Invoke-Test, /Users/vors/dev/Pester/Functions/It.ps1: line 258
        at ItImpl, /Users/vors/dev/Pester/Functions/It.ps1: line 207
        at It, /Users/vors/dev/Pester/Functions/It.ps1: line 121
        at <ScriptBlock>, /Users/vors/dev/Pester/Functions/Output.Tests.ps1: line 277
        at DescribeImpl, /Users/vors/dev/Pester/Functions/Describe.ps1: line 161
        at Describe, /Users/vors/dev/Pester/Functions/Describe.ps1: line 86
        at Context, /Users/vors/dev/Pester/Functions/Context.ps1: line 60
        at <ScriptBlock>, /Users/vors/dev/Pester/Functions/Output.Tests.ps1: line 248
        at DescribeImpl, /Users/vors/dev/Pester/Functions/Describe.ps1: line 161
        at Describe, /Users/vors/dev/Pester/Functions/Describe.ps1: line 86
        at <ScriptBlock>, /Users/vors/dev/Pester/Functions/Output.Tests.ps1: line 152
        at InModuleScope, /Users/vors/dev/Pester/Functions/InModuleScope.ps1: line 84
        at <ScriptBlock>, /Users/vors/dev/Pester/Functions/Output.Tests.ps1: line 120
        at <ScriptBlock>, /Users/vors/dev/Pester/Pester.psm1: line 792
        at Invoke-Pester<End>, /Users/vors/dev/Pester/Pester.psm1: line 807
        at <ScriptBlock>, <No file>: line 1
```

Then I hit the #827 and it just tooks too much time to wait for all the tests to finish.

**Comment by it-praktyk** [comment]
OK, I don't have to export functions which are parts of the current pull request.

But what is it most elegant/convenient way to invoke these function inside Pester code itself and tests of Pester code?

**Comment by dlwyatt** [comment]
In tests, use InModuleScope. Within pester itself, just call them. They're part of the module, just not exported to users.

**Comment by it-praktyk** [comment]
OK, thx. It was too easy or I'm too tired. Greetings from the middle of the night in Europe.

**Comment by it-praktyk** [comment]
@vors, thx for the report.

**Pull request closed without merging**
