### PR TITLE
Add missing test file

### PR DESCRIPTION
**Pull request by fflaten**
## PR Summary
I'm not sure how #2523 passed checks, but this file was not committed. Discovered in backport PR #2524 where tests failed.

## PR Checklist

- [x] PR has meaningful title
- [x] Summary describes changes
- [x] PR is ready to be merged
  - If not, use the arrow next to `Create Pull Request` to mark it as a draft. PR can be marked `Ready for review` when it's ready.
- [x] Tests are added/update *(if required)*
- [ ] Documentation is updated/added *(if required)*

### CODE REVIEW

**Comment by nohwnd** [comment]
Did you have closer look on why the tests in the pipeline did not fail when the file was missing?

**Comment by fflaten** [comment]
The tests are skipped in v6 pipeline due to use of `test.ps1 -CC` parameter.

**Comment by nohwnd** [comment]
Yeah I need to fix that, or run those tests separately. I think I disabled them because they were turning off tracing and breaking the overall code coverage.

**Comment by nohwnd** [comment]
https://github.com/pester/Pester/issues/2526

**Pull request merged**
