### PR TITLE
Add advanced tag filtering options

### LINKED ISSUE #608: Invoke-Pester for tests, where all of numerus tags are present
`Invoke-Pester -Tag @('A', 'B')` runs any tests tagged with "A" or "B".

```powershell
Describe 'foo1' -Tag 'A' {
    It 'should be ok' {
        1 | should be 1
    }
}

Describe 'foo2' -Tag 'B' {
    It 'should be ok' {
        1 | should be 1
    }
}

Describe 'foo3' -Tag @('A', 'B') {
    It 'should fail' {
        1 | should be 1
    }
}

```

For example, here all 3 tests would be executed.

We have a situation, where it's desirable to run tests **when all tags** are present.
So in this case, only "foo3" would be run.

Changing the meaning of `-Tag` is obviously not an option.
I'd like to propose to add a new parameter, maybe `-TagAll` that enable this scenario.

At the same time, we may rename `-Tag` into `-TagAny` and add alias `-Tag` to this parameter.
Also, maybe aliasing `-ExcludeTag` with `-TagExclude` will make exportability of all these 3 related parameters better.

For the context, I'm working on https://github.com/PowerShell/PowerShell/pull/2280 where I'm adding a new tag "RequireAdminOnWindows" and this tag is orthogonal to our current used tags.

### PR DESCRIPTION
**Pull request by hbuckle**
## 1. General summary of the pull request

Adds a new parameter AdvancedTag to Describe to specify tags as a hashtable and a corresponding TagFilter parameter to Invoke-Pester that allows for granular filtering of tags using a scriptblock

Fix #608 

### TODO
- [ ] Documentation

### CODE REVIEW

**Comment by hbuckle** [comment]
I can't seem to get the PowerShell 2 run to pass and I've no way of testing it locally, any ideas?

**Comment by nohwnd** [comment]
@hbuckle thanks for the PR but I won't be merging this into v4 I am sorry. The tagging in v4 barely works for the basic cases, and adding yet another concept to tagging is confusing, and would be hard for me to support going forward. 

In Pester v5 the tagging works much better, and while it is not as flexible as what you provided here right now, it can be easily extended to do more, by allowing the filter to take a scriptblock. 

I am definitely interested in why you are using  hashtable of tags together with a scriptblock. Why tags are not an array of strings? 🙂  What advantage it brings? Maybe there is some idea that I never considered. 🙂

**Comment by hbuckle** [comment]
@nohwnd thanks for the feedback - hashtable and scriptblock seemed much more natural for writing filters than a string array. For example we have tests that need to run at different points during a release and for different environments. So a simplified example could look like

```powershell
Describe "Linting" { } -Tag @{
  when         = "before_plan"
  environments = @("ci")
}

Describe "Policy" { } -Tag @{
  when         = "before_apply"
  environments = @("ci", "staging", "production")
}

Describe "Integration" { } -Tag @{
  when         = "after_apply"
  environments = @("staging")
}

Describe "Smoke" { } -Tag @{
  when         = "after_apply"
  environments = @("production")
}

Invoke-Pester -Filter {
  $tags.when -eq "before_plan" -and
  $tags.environment -contains "$(Release.EnvironmentName)"
}

Invoke-Pester -Filter {
  $tags.when -eq "before_apply" -and
  $tags.environment -contains "$(Release.EnvironmentName)"
}
```

**Comment by nohwnd** [comment]
That definitely looks interesting, I saw other requests to be able to add more metadata to a test. I think this could be merged with that and added to v5. I would just need to think a bit more about how it works in relation to filtering, testcases, addinge metadata to parent blocks, and being able to print the info to the screen. 🙂

**Comment by nohwnd** [comment]
Closing this for the reasons above,

**Comment by nohwnd** [comment]
Need to look into this if it can be retargetted for v5, or if the functionality needs to be written from scratch there.

**Comment by nohwnd** [comment]
we will need to make this from scratch. thanks for the code  :)

**Pull request closed without merging**
