### PR TITLE
Filter excluded tests from NUnit results

### LINKED ISSUE #1662: Bug: v5: Discovery creates null test-case elements in the NUnit xml file
## 1. General summary of the issue

When running Pester, it now includes all the discovered tests even when you specify a -Tag, the tests that fall outside the tag filter, get deposited in the xml file. 

## 2. Describe Your Environment
Pester version     : 5.0.3 C:\Program Files\WindowsPowerShell\Modules\Pester\5.0.3\Pester.psd1
PowerShell version : 5.1.14409.1018
OS version         : Microsoft Windows NT 6.3.9600.0

$Env:PSModulePath: C:\Users\myAccount\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\

## 3. Expected Behavior

Only the tests that were found in the filter should be included in the NUnit file.

## 4.Current Behavior

All tests found in discover even if they were or were not in the tags filter are included in the nunit file.

```
<test-suite type="TestFixture" name="All Environment Tests" executed="True" result="Success" success="True" time="0" asserts="0" description="All Environment Tests">
            <results>
              <test-suite type="TestFixture" name="All Environment Tests.Get-WindowsFeature" executed="True" result="Success" success="True" time="0" asserts="0" description="All Environment Tests.Get-WindowsFeature">
                <results>
                  <test-suite type="ParameterizedTest" name="All Environment Tests.Get-WindowsFeature.should be installed: &lt;DisplayName&gt;: '&lt;Name&gt;'" executed="True" result="Success" success="True" time="0" asserts="0" description="should be installed: &lt;DisplayName&gt;: '&lt;Name&gt;'">
                    <results>
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                    </results>
                  </test-suite>
                </results>
              </test-suite>
              <test-suite type="TestFixture" name="All Environment Tests. - TLS Settings" executed="True" result="Success" success="True" time="0" asserts="0" description="All Environment Tests. - TLS Settings">
                <results>
                  <test-case description="" name="" time="0" asserts="0" success="False" />
                  <test-case description="" name="" time="0" asserts="0" success="False" />
                  <test-case description="" name="" time="0" asserts="0" success="False" />
                  <test-case description="" name="" time="0" asserts="0" success="False" />
                  <test-case description="" name="" time="0" asserts="0" success="False" />
                  <test-case description="" name="" time="0" asserts="0" success="False" />
                  <test-case description="" name="" time="0" asserts="0" success="False" />
                  <test-case description="" name="" time="0" asserts="0" success="False" />
                </results>
              </test-suite>
              <test-suite type="TestFixture" name="All Environment Tests.- Permissions" executed="True" result="Success" success="True" time="0" asserts="0" description="All Environment Tests.- Permissions">
                <results>
                  <test-suite type="ParameterizedTest" name="All Environment Tests.- Permissions.should have FullControl to C:\JHA" executed="True" result="Success" success="True" time="0" asserts="0" description="should have FullControl to C:\JHA">
                    <results>
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                    </results>
                  </test-suite>
                  <test-suite type="ParameterizedTest" name="All Environment Tests.- Permissions.should have FullControl to C:\Program Files\JHA" executed="True" result="Success" success="True" time="0" asserts="0" description="should have FullControl to C:\Program Files\JHA">
                    <results>
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                      <test-case description="" name="" time="0" asserts="0" success="False" />
                    </results>
                  </test-suite>
                </results>
              </test-suite>
              <test-case description="" name="" time="0" asserts="0" success="False" />
              <test-case description="" name="" time="0" asserts="0" success="False" />
              <test-case description="" name="" time="0" asserts="0" success="False" />
              <test-case description="" name="" time="0" asserts="0" success="False" />
              <test-case description="" name="" time="0" asserts="0" success="False" />
              <test-case description="" name="" time="0" asserts="0" success="False" />
              <test-case description="" name="" time="0" asserts="0" success="False" />
              <test-case description="" name="" time="0" asserts="0" success="False" />
              <test-case description="" name="" time="0" asserts="0" success="False" />
              <test-case description="" name="" time="0" asserts="0" success="False" />
              <test-case description="" name="" time="0" asserts="0" success="False" />
              <test-case description="" name="" time="0" asserts="0" success="False" />
              <test-case description="" name="" time="0" asserts="0" success="False" />
              <test-case description="" name="" time="0" asserts="0" success="False" />
              <test-suite type="ParameterizedTest" name="All Environment Tests.Hard Disk should be at least 15% free, and found &lt;FreeSpacePercent&gt;% free on &lt;DriveLetter&gt;" executed="True" result="Success" success="True" time="0" asserts="0" description="Hard Disk should be at least 15% free, and found &lt;FreeSpacePercent&gt;% free on &lt;DriveLetter&gt;">
                <results>
                  <test-case description="" name="" time="0" asserts="0" success="False" />
                  <test-case description="" name="" time="0" asserts="0" success="False" />
                </results>
              </test-suite>
              <test-suite type="ParameterizedTest" name="All Environment Tests.Hard Disk &lt;DriveLetter&gt; should have a minimum of 60GB, and found &lt;totalHDSize&gt;GB" executed="True" result="Success" success="True" time="0" asserts="0" description="Hard Disk &lt;DriveLetter&gt; should have a minimum of 60GB, and found &lt;totalHDSize&gt;GB">
                <results>
                  <test-case description="" name="" time="0" asserts="0" success="False" />
                  <test-case description="" name="" time="0" asserts="0" success="False" />
                </results>
              </test-suite>
              <test-suite type="ParameterizedTest" name="All Environment Tests.should have acceptable latancy" executed="True" result="Success" success="True" time="0" asserts="0" description="should have acceptable latancy">
                <results>
                  <test-case description="" name="" time="0" asserts="0" success="False" />
                </results>
              </test-suite>
            </results>
          </test-suite>
        </results>
```

## 5. Possible Solution

Let the -tag's filter be explicit and work like it used to. Why include tests that never ran but were only discovered?

## 6. Context

I am trying to use the extent framework to display pester nUnit results. This worked in v4, v5 broke it. I have worked around the problem by finding the folder paths and now specifying all the -Path's, The -tags parm is no longer useful.

### PR DESCRIPTION
**Pull request by deejaygraham**
## 1. Filter excluded test from the NUnit Results

 Fix #1662 

Tests the ShouldRun property of a test result to determine if it was included or excluded from the run using tag or exclude tag.
Added two new tests to demonstrate the fix. Looking for feedback on situation where describe block is filtered out so the NUnit report has a test suite reported as succeeded but contains no results or test cases.

### CODE REVIEW

**Comment by nohwnd** [comment]
Thanks for paving the way, very helpful! 🙌

I looked at the xml output (`$XmlResult.OuterXml | clip, and then paste that into VSCode document with XML language mode set, and format it by alt+shift+f). There were also containers and blocks included, so I looked at the callstack from the point where you added the condition and excluded them as well. 

And I had hard time getting the tests because I could not remember which should be excluded and which should be not, so I named them accordingly to avoid thinking.

**Comment by nohwnd** [comment]
Btw if you write the related issue in code like this `Fix #1662`, it won't close it (I think), and even if it did you lose on easily navigating to the related issue.

**Comment by deejaygraham** [comment]
It took me a while to work out understand what the behaviour of the include tag vs exclude tag was.

**Comment by deejaygraham** [comment]
Yes, the containers and actions were what I was unclear on because that left some orphan elements in the report. Thanks!

**Comment by nohwnd** [comment]
I was not criticizing, just giving context why I did that. I need to come back in a month or a year and understand what is happening. And I was not able to easily follow now, while having the context. So I just renamed them, now whey I see Excluded in the xml output I know it should be excluded 🙂

**Comment by nohwnd** [comment]
> Yes, the containers and actions were what I was unclear on because that left some orphan elements in the report. Thanks!

Both the container and block actually go through this function, so they could be excluded in a single place here: 
https://github.com/pester/Pester/pull/1686/files#diff-9d06394664e89fba6b48c05ff5001458R243-R245

But I don't want the overhead of calling the function just to return from it, and it is more obvious the way it is now.

**Pull request merged**
