### PR TITLE
Cleanup about_* help topics and extract PesterConfiguration docs to about_PesterConfiguration

### LINKED ISSUE #2491: Remove or update included about_ help files
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [open documentation issues](https://github.com/pester/Pester/issues?q=is%3Aissue+label%3ADocumentation+is%3Aopen)

### Where did you see it?

Pester (latest)

### Function name

about_*

### What is the issue?

Pester includes offline help in about_* format which has not been updated for Pester v5. Before releasing v6 there's a choice to be made:

- Update?
- Remove and solely depend on https://pester.dev and command help? Maybe keep about_Pester as a simple introduction and reference to the website?

Related files found here https://github.com/pester/Pester/tree/main/src/en-US:
about_BeforeEach_AfterEach
about_Mocking
about_Pester 
about_Should
about_TestDrive

### PR DESCRIPTION
**Pull request by fflaten**
## PR Summary
- Removes outdated about_* help topics that are no longer maintained.
- Updates `about_Pester` as a quick introduction pointing the user to the website for full docs.
- Moves PesterConfiguration reference docs to `about_PesterConfiguration` to simplify `New-PesterConfiguration` help and match similar extracted docs on website to Usage\Configuration. See pester/docs#316
  - Includes Type for each configuration option.

Fix #2491
Related https://github.com/pester/docs/issues/280#issuecomment-2156743657

## PR Checklist

- [x] PR has meaningful title
- [x] Summary describes changes
- [x] PR is ready to be merged
  - If not, use the arrow next to `Create Pull Request` to mark it as a draft. PR can be marked `Ready for review` when it's ready.
- [ ] Tests are added/update *(if required)*
- [x] Documentation is updated/added *(if required)*

### CODE REVIEW

**Comment by fflaten** [comment]
Nice. Should I create a matching PR for v5?

V6-docs PR includes the same PesterConfiguration in usage/Configurarion for v5.

**Comment by nohwnd** [comment]
Backport bot? :)

Odesláno z aplikace Outlook pro iOS<https://aka.ms/o0ukef>
________________________________
Od: Frode Flaten ***@***.***>
Odesláno: Monday, July 1, 2024 6:51:04 PM
Komu: pester/Pester ***@***.***>
Kopie: Jakub Jareš ***@***.***>; State change ***@***.***>
Předmět: Re: [pester/Pester] Cleanup about_* help topics and extract PesterConfiguration docs to about_PesterConfiguration (PR #2518)


Nice. Should I create a matching PR for v5?

V6-docs PR includes the same PesterConfiguration in usage/Configurarion for v5.

**Comment by fflaten** [comment]
Yeah, I'll use it as a draft. Need some adjustments to build script + generated docs for v5. 🙂

**Comment by fflaten** [comment]
Guess it's manual cherry pick then 😁

**Pull request merged**
