### PR TITLE
Cleaning of code - PSScriptAnalyzer rules

### PR DESCRIPTION
**Pull request by it-praktyk**
Violations reported by PSScriptAnalyzer v.1.11.0

The related issue #700 
Replace the pull request #707

### CODE REVIEW

**Comment by dlwyatt** [comment]
I really don't care what script analyzer thinks. I prefer the aliases "select", "where", etc. However, I do think we should get rid of the instances of % and ?

I'm also fine with positional parameters when the meaning is obvious, regardless of the whiny linting tool. :)

**Comment by it-praktyk** [comment]
I hope that your personal preferences will not be block of merge that PR ;-)

By mistake I left proposed - under #701 - tests and the current results you can see on the CI results page [here](https://build.powershell.org/viewLog.html?buildId=10199&buildTypeId=Pester_TestPester&guest=1).

What about these?

W. alias Whiny ;-)

**Comment by dlwyatt** [comment]
I won't be merging this as-is.  `ForEach-Object -Process` just makes me want to scream.  :P

**Comment by it-praktyk** [comment]
Under verifying other rules used by PSScriptAnalyzer I found real bug :-/

2017-03-31 21_43_51-pester tests ps1 head - pester tests ps1 - pester - visual studio code

**Comment by it-praktyk** [comment]
@Jaykul , could you check ? The partial result of test below
```
Pester source code doesn't violate the PSScriptAnalzyer rule PSUseDeclaredVarsMoreThanAssignments
      File: C:\Users\<USERNAME>\Pester\Functions\Gherkin.ps1, Line: 4
      File: C:\Users\<USERNAME>\Pester\Functions\Gherkin.ps1, Line: 339
```
Thank you.

**Comment by it-praktyk** [comment]
The related issue #768

**Comment by it-praktyk** [comment]
Guys, I did that work because I think that cleaner code is a better code.

As you can observer I closed my previous pull request #701 because the PSScriptAnalyzer rules can't be used automaticaly for the code of Pester project.

I hope that you will merge it even if you don't agree with some principles of cleaner coding.

W. alias Whiny ;-)

**Comment by it-praktyk** [comment]
The CI validation for the current branch failed due to the bug #768 - please consider merge or rebase a code after reviewing and correcting the mentioned bug.

**Comment by dlwyatt** [comment]
> I think that cleaner code is a better code.

I totally agree with that.  However, I don't think that the script analyzer rules produce cleaner code in all cases:

- The `*-Object` cmdlets are mostly silly names, likely created only because they had agreed to name everything with Verb-Noun (which is still silly, because `Where` and `ForEach` aren't verbs anyway.)

- Parameter names are, in some cases, just noise.  `-Process` on `ForEach-Object` is one example.  When you're only using that block (which is probably 95% of the uses), it's perfectly clear without the parameter name.  If you are passing in multiple blocks, then parameter names are appropriate.  Another common case is where the first positional parameter has a name that exactly matches the noun of the cmdlet:  `Test-Path -Path $somePath` is silly, when `Test-Path $somePath` is still just as clear.  In the case of `Join-Path`, I go even farther and use both arguments by position:  `Join-Path $parent $child` is already easy to read.

- I also use positional parameters when calling `New-Object`, mostly because it just feels right after typing `new TypeName(constructorParameters)` in C-Style languages for so long.  Right or wrong, that's just my preference, and you'll see the same thing all over the place (even in Microsoft's own code.)  I prefer the look of `New-Object TypeName($params)`, even though the syntax is kind of abusing the PowerShell parser a bit.

I'm fine with making some of these changes to clean up the code, but not all of them, and I don't expect Pester's code to ever match the stock script analyzer rules 100%.

**Comment by Jaykul** [comment]
I'll check the line mentioned, that looks bad.
But I agree about parameters and aliases on the -Object commands, those "rules" are silly.

**Comment by it-praktyk** [comment]
I just removed removed named parameters.

**Comment by dlwyatt** [comment]
Getting there :)  I'll strip out the -Object names and merge it later tonight.

**Comment by it-praktyk** [comment]
So, generally will you revert big part of the commit 89022f6b8db263206fecbe553af5a37dccdafe5f ? Even if I removed names of parameters introduced by it?

**Comment by it-praktyk** [comment]
@Jaykul , did you check https://github.com/pester/Pester/pull/766#issuecomment-290829140 ?

**Comment by Jaykul** [comment]
@it-praktyk I don't remember. I'll try to look tonight...

**Comment by Jaykul** [comment]
@it-praktyk finally checked. Both those lined can just be removed. See #801

**Comment by it-praktyk** [comment]
@Jaykul, thank you :-)

**Comment by it-praktyk** [comment]
Thank you

**Pull request merged**
