### PR TITLE
Found a spelling error, and added one new example

### PR DESCRIPTION
**Pull request by LukeBG**
I found a spelling error. I added an example that I was looking for. What do you think?

### CODE REVIEW

**Comment by LukeBG** [comment]
I see I that merging against your remote branch It-documenatation-update could be a mistake with that lengthy commit history.

**Comment by dlwyatt** [comment]
If you open a pull request, just target our Master branch.  :)  It's a good idea to create your own branch to hold the PR, though; otherwise any commits you make to your copy of Master will show up in the PR.

**Comment by LukeBG** [comment]
Okay, I think I "close and comment" if I want to try it again?

**Comment by dlwyatt** [comment]
Yep.

**Comment by LukeBG** [comment]
Got it! :)

**Pull request closed without merging**
