### PR TITLE
Update issue templates to forms syntax

### PR DESCRIPTION
**Pull request by fflaten**
## PR Summary
[Issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) have been in beta for public repositories for a while now and looks stable. Will provide a cleaner user experience by removing the current markdown comments used for help text.

- Updated templates to forms syntax
- Disabled legacy issue template currently available using the "Don’t see your issue here? Open a blank issue." link

Demo: https://github.com/fflaten/githubsandbox/issues/new/choose

## PR Checklist

- [x] PR has meaningful title
- [x] Summary describes changes
- [x] PR is ready to be merged
  - If not, use the arrow next to `Create Pull Request` to mark it as a draft. PR can be marked `Ready for review` when it's ready.
- [ ] Tests are added/update *(if required)*
- [ ] Documentation is updated/added *(if required)*

### CODE REVIEW

**Comment by fflaten** [comment]
Con: Doesn't work in mobile app yet. Redirects the user to browser when selecting the issue template.

**Comment by nohwnd** [comment]
Looks good, what needs to be finished? Or are you waiting for the forms to be available on mobile?

**Comment by fflaten** [comment]
Wasn't sure if we should split "location" in command help form to individual input-fields for Pester version and function name?

Do we even need to ask for Pester version anymore considering we always refer to latest version?

**Comment by fflaten** [comment]
> Wasn't sure if we should split "location" in command help form to individual input-fields for Pester version and function name?
> 
> Do we even need to ask for Pester version anymore considering we always refer to latest version?

[Demo using input-fields](https://github.com/fflaten/githubsandbox/issues/new?assignees=&labels=Documentation&template=commandhelp_issue2.yml)

Better?

**Comment by nohwnd** [comment]
I find having so many required fields quite annoying, but let's try it :) 

As for the dropdown in docs issue, I would add Other as an option as well. 

For the issue template, I would at least get rid of the Current behavior field, I never got why people force me to state my issue in the summary, and the re-iterate that in current behavior. 

What do you think about making it:

What is the issue?*:
Expected behavior*: 
Steps to reproduce: 
Describe your environment: 
Possible solution?

**Comment by fflaten** [comment]
Sounds good. See latest update. I've also submitted a similar PR (pester/docs#186) in docs-repo, with forms and direct link to the command help form here.

**Review by nohwnd — APPROVED** [review]

**Pull request merged**
