### PR TITLE
Deprecate Get-TestDriveItem in Pester v. 4.0, update help

### PR DESCRIPTION
**Pull request by it-praktyk**
The issue #665

### CODE REVIEW

**Comment by it-praktyk** [comment]
I corrected my code (trailing spaces) and commited once again with the --amend what triggered tests what failed :-( 

Can you check?

selection_008

**Comment by nohwnd** [comment]
Lol my bad.... never add commemts to your build definition without actually making them commemts :D


Jakub Jareš

.NET, Pester, PowerShell
t 00420603800578<tel:00420603800578>
e me@jakubjares.com<mailto:me@jakubjares.com>
t @nohwnd

16. 1. 2017 v 14:43, Wojciech Sciesinski <notifications@github.com<mailto:notifications@github.com>>:


I corrected my code (trailing spaces) and commited once again with the --amend what triggered tests what failed :-(

Can you check?

[selection_008]<https://cloud.githubusercontent.com/assets/4910261/21985244/fd909bfe-dbf9-11e6-96d9-7ec7e6540da8.png>

**Comment by nohwnd** [comment]
@it-praktyk your PR passes now. do you plan any other changes? hopefully I will merge it today/tomorrow.

**Comment by it-praktyk** [comment]
I'll correct trailling spaces in other my pull request also - probably tonight.

**Comment by it-praktyk** [comment]
The pull requests #668 , #670 , #669 are correct now.

For the DevelopmentV4 branch I'll prepare analogical updates soon.

**Pull request merged**
