### PR TITLE
Gherkin v2 -- err, v5

### PR DESCRIPTION
**Pull request by fourpastmidnight**
## 1. General summary of the pull request

Initial work on revamping the Gherkin side of the framework as described in #1245. This is only the first few commits. Some notes on the commits in this branch:

* This originally started off as my branch `skip-rest-of-steps-after-frist-non-passing-step` on top of v4.4.x of Pester. As such, there are 2 commits which made changes to `Functions\Gherkin.ps1` and `Functions\Output.ps1`. These commits will eventually be dropped.
* Almost certainly this Draft PR will not be passing the tests.
* This is being put out there to gather feedback as early as possible. Be nice in your critique 😉 I'm only trying to make things better. But I welcome advice, guidance, and help.

### CODE REVIEW

**Comment by fourpastmidnight** [comment]
Obviously, this needs quite a bit more work to be "v5-compliant". I was "out of the loop" for a while and so nothing runs under v5. But that's OK. I'm guessing one of the first things to be done is create a `Pester.Gherkin.psm1` script module...

**Comment by fourpastmidnight** [comment]
Ok, what's the replacement for `New-PesterState`? Asking just in case someone answers before I figure it out. 😄

**Comment by fourpastmidnight** [comment]
Hmm, I see in `Pester.Runtime.psm1` a script-level variable `$state` is created. It seems to provide a similar function to the former `PesterState` object. Okay, and it seems to be a module-wide state object.

**Comment by nohwnd** [comment]
Closing this up, it's WIP, and current Pester does not support Gherkin anymore. As we discussed, feel free to fork the repo and start implementing Gherkin on your own.

**Pull request closed without merging**
