### PR TITLE
Filter by scriptblock position

### PR DESCRIPTION
**Pull request by nohwnd**
ScriptBlockFilter filters top-level describes by position of the Fixture instead of filtering by name, this is for plugin usage to accomodate tests that expand properties in the describe name, and so AST and runtime values in the name do not match.

See https://github.com/PowerShell/PowerShellEditorServices/issues/827

### CODE REVIEW

**Comment by nohwnd** [comment]
```powershell 
# file run.ps1
get-module pester | remove-module
import-module .\Pester.psd1

# runs a and b but not e
$o = New-PesterOption -ScriptBlockFilter @(
    # describe a
    @{ Path = "C:\Users\nohwnd\Desktop\filtering on sb position.ps1"; Line = 1 }
    # describe b
    @{ Path = "C:\Users\nohwnd\Desktop\filtering on sb position.ps1"; Line = 5 }
    # describe c, but it does not apply on child blocks
    @{ Path = "C:\Users\nohwnd\Desktop\filtering on sb position.ps1"; Line = 6 }
)
invoke-pester -Script "~\Desktop\filtering on sb position.ps1" -PesterOption $o

```
```powershell
# file filtering on sb position.ps1

**Comment by nohwnd** [comment]
I don't see anything in my changes that should cause such a bug, and I don't see it running recursively in your output. So we understand each other what this change is supposed to do? I just added a filter that works like the TestName filter, but it filters on different criteria. So the files that you give it will still run, it does not filter the paths until the scriptblock is reached, if you want one file to run you should still give it just a one file to run.

**Comment by bergmeister** [comment]
It was a mistake that I made locally when i wasn't aware that I had to specify the path inside the filter as well, sorry, I edited my comment.

**Comment by bergmeister** [comment]
After I upstreamed my PSES and vs-code branches, I have it working now end to end. The big question now to @rkeithhill is if we need to have a check on the Pester version or if we should download Pester the minimum required v ersion as a fallback similar to how the extension does it for PSSA?
image

**Comment by rkeithhill** [comment]
I think we'd need to add the version check regardless of whether Pester ships with the extension.  A user could have loaded a specific (older) version of Pester into the PSIC that doesn't support this.

RE shipping Pester with the question.  That is probably something @rjmholt and/or @TylerLeonhardt should answer.

**Comment by TylerLeonhardt** [comment]
Yeah we tack on the end of the PSModulePath so even _if_ we ship Pester, a version check is the right way to go here.

I don't think we should ship Pester personally but I would love to use the extension to get people on the newer version in an semi-unobtrusive way.

**Comment by bergmeister** [comment]
@nohwnd Thanks, I created [this](https://github.com/PowerShell/vscode-powershell/issues/1710) issue for the technical discussion of how to implement it in the extension

**Pull request merged**
