### PR TITLE
Added an EXAMPLE section to About_Pester

### PR DESCRIPTION
**Pull request by juneb**

### CODE REVIEW

**Comment by nohwnd** [comment]
Hello, 
you should really create a feature branch for every PR that you plan to do. If you just PR from your master, to our master we will be able to see all changes that you do to your master (PR is just a pointer to a branch, not a snapshot). Plus at this point there are unresolved merge conflicts in your code.

You have two options now: a) fix the merge conflicts, rebase and squash on upstream master, force push and then wait for us to merge it. 
b) move your changes to different branch, cleanup there and do new PR.

Also we prefer rebase over merge in this repository. So it would be better if you rebased and squashed your changes so they ideally appear as a single commit. 

The flow will be something like this: 
```
git checkout master
git branch AddExamplesToAbout
git checkout AddExamplesToAbout
.. cleanup your changes
git add .
git commit -m"Add example to about"
git rebase -i upstream/master
... pick single change and squash the others
```

If you need any help with that let me know. My mail is also my Skype id.

**Comment by juneb** [comment]
Sorry for the trouble. I don't see any merge conflicts -- they don't show up in my fork. I don't know how to fix merge conflicts that I can't see. I don't know how to use rebase or squash.

I can create a branch, but I'm not sure why I need to do this. I want you to see the changes, in case there are errors.

**Comment by nohwnd** [comment]
No problem, happens to everyone, believe me. :) 

Merge conflict was not the right word, it's merge messages in 23dbae883e4c5891f65c50494b470686856dae73 and 81c3ca98a06e7986efe3c46c0d52ee111d127849 this makes the PR more difficult to follow than if it would be just a single commit. That way I can see all the changes that are proposed without hunting around multiple commits. Plus it makes the history of the project easier to read because rebasing keeps the history linear without all the unnecessary merge messages. Plus it might force us to solve the same merge conflicts more than once.

The other thing is creating branch for your changes, that simply enables you to have more PR open at the same time, and avoid accidental changes to them. If you now commit+push to your master the change will propagate to this PR. 


So you can rebase and update the commit yourself, or I can do it and merge it, this is what the process should be for you:
```
git rebase -i upstream/master # to rebase on latest code
interactive rebase file will open...
pick 1b86de6 Added Example section #keep as is
fixup 81c3ca9 Added example section #change action to fixup
... you will get a message about merge conflicts
 git diff # to see the conflicts
code en-US/about_Pester.help.txt #or other editor 
git add . #add changes so you can continue with rebase
git rebase --continue 
... file will open with your commit messages, edit it or just close it
... you should get a message that rebase was successful
git log --graph --oneline --decorate # to see that you are one commit in front of master
git push --force # to update the PR
```

**Comment by juneb** [comment]
Okay, please reject this PR. I'll revise and resubmit.

**Pull request closed without merging**
