### PR TITLE
Fix JaCoCo report so it can be processed by Codecov.io

### LINKED ISSUE #1419: Codecov cannot process JaCoCo reports generated by Pester
## 1. General summary of the issue

The JaCoCo format that is output by Pester does not follow the schema since it missing the attributes `mb` and `cb`, and the file is output with the encoding "UTF-8 with BOM".
 
See more information in the Codecov forum
https://community.codecov.io/t/error-while-processing-jacoco-reports-generated-by-pester-powershell/139/5

A good article explaining the different attributes.
https://stackoverflow.com/questions/33868761/how-to-interpret-the-jacoco-xml-file

## 2. Describe Your Environment

Using build worker in Azure Pipelines.

## 3. Expected Behavior

The JaCoCo format output by Pester should not need post-processing of the file.

## 4.Current Behavior

Need to pre-process the file before upload to Codecov.io.
```powershell
$xml = Select-Xml -Path './output/testResults/CodeCov*.xml' -XPath '.'

$nodes = $xml.Node.SelectNodes("/report/package/sourcefile/line");
foreach ($node in $nodes)
{
    $node.SetAttribute('mb', 0)
    $node.SetAttribute('cb', 0)
}

$xml.Node.Save("./output/testResults/JaCoCo_coverage.xml")

# This changes the encoding on the file to UTF-8 without BOM.
$fileContent = Get-Content -Path './output/testResults/JaCoCo_coverage.xml' -Encoding 'Unicode' -Raw
$fileContent | Out-File -FilePath './output/testResults/JaCoCo_coverage.xml' -Encoding 'ascii'
``` 

## 5. Possible Solution

Add the two missing attributes `mb` and `cb` and hard-code with `0` (not sure Pester can see branches).  

https://github.com/pester/Pester/blob/30c5f7e3f1a045589c0bbc4d34b0961fdfbd5b92/Functions/Coverage.ps1#L746-L750

Change the file that is written to use `'ASCII'` as the encoding (= "UTF-8 _without_ BOM")

https://github.com/pester/Pester/blob/9b314e4a74a943d8ab89a6755b583679007c768e/Pester.psm1#L1158

## 6. Context

Need to do pre-processing of the XML which unnecessarily complicates the pipeline.

### PR DESCRIPTION
**Pull request by johlju**
## 1. General summary of the pull request

- Fix missing attributes in the JaCoCo report so it can be processed by Codecov.io.
- Add new parameter `CodeCoverageOutputFileEncoding` to cmdlet `Invoke-Pester` so that the user can change the encoding.

Since this repository have enabled format on save a few whitespace changes was introduces as well.

I can update the WIki once this PR is through. 

- Fixes #1419

---
This change is [Reviewable](https://reviewable.io/reviews/pester/pester/1420)

### CODE REVIEW

**Comment by johlju** [comment]
The job for PS 2.0 failed because the job is not allowed to run more than 3 minutes 🤔

**Comment by johlju** [comment]
@nohwnd This is ready for review.

**Comment by nohwnd** [comment]
@johlju `Process is terminating due to StackOverflowException.` You sure?

**Comment by johlju** [comment]
image

**Comment by nohwnd** [comment]
In creased it to 5 minutes to see if it helps. :)

**Comment by johlju** [comment]
Closing and reopening to kick off the tests again.

**Comment by johlju** [comment]
@nohwnd worked raising the timeout. 🙂

**Comment by nohwnd** [comment]
K let's merge it with the parameter.

**Pull request merged**
