### PR TITLE
Create scenario for every example

### PR DESCRIPTION
**Pull request by cgnuechtel**
* Every single example is a scenario, even inside an example set
* We create a unique scenario name by using an index

Implementation for #1167

### CODE REVIEW

**Comment by cgnuechtel** [comment]
Merge with #1166 here:

https://github.com/cgnuechtel/Pester/tree/merge-CreateScenarioForEveryExample-GherkinMultipleLanguages

**Comment by nohwnd** [comment]
@fourpastmidnight / @Jaykul could you give this a look and tell me if I should merge please :)

**Comment by nohwnd** [comment]
@cgnuechtel Also thanks for contributing 👍

**Comment by fourpastmidnight** [comment]
@nohwnd I need to review this some more, but after more discussion wich @cgnuechtel, the concept presented in this PR should be merged and is (mostly) orthogonal to the work I was doing on #1142.

**Pull request merged**
