### PR TITLE
Fix help for Invoke-Pester

### PR DESCRIPTION
**Pull request by fflaten**
## PR Summary
Fixes RELATED LINKS in `Invoke-Pester` help. 
Commented placeholder for ScriptAnalyzer suppression-rule got too close to the comment-based help which resulted in this issue:

```
RELATED LINKS
    https://pester.dev/docs/quick-start
    https://pester.dev/docs/commands/Invoke-Pester
    https://pswiki.net/invoke-pester-pester/
    https://pester.dev/docs/commands/Describe
    about_Pester
    
    Currently doesn't work. $IgnoreUnsafeCommands filter used in rule as workaround
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute('Pester.BuildAnalyzerRules\Measure-SafeComands', 'Remove-Variable', Justification = 'Remove-Variable can't remove "optimized variables" when using "alias" for Remove-Variable.')] 
```

Also updates examples with missing description.

## PR Checklist

- [x] PR has meaningful title
- [x] Summary describes changes
- [x] PR is ready to be merged
  - If not, use the arrow next to `Create Pull Request` to mark it as a draft. PR can be marked `Ready for review` when it's ready.
- [ ] Tests are added/update *(if required)*
- [ ] Documentation is updated/added *(if required)*

### CODE REVIEW

**Comment by fflaten** [comment]
@nohwnd Target rel/5.1.1xx to fix it earlier? It'll probably fix broken example 3+4 in pester/docs#78
What's you plan for including these hotfixes in 5.2? New PRs later to merge the updates into v5.0?

**Comment by nohwnd** [comment]
@fflaten re-targetted. 

> What's you plan for including these hotfixes in 5.2?

No need for extra PR. I will forward merge into v5.0.

**Comment by fflaten** [comment]
Great 👍

**Pull request merged**
