### PR TITLE
Fix broken assertions link in help

### PR DESCRIPTION
**Pull request by fflaten**
## PR Summary
Fixes a broken link in `Should` help for the custom assertions page at https://pester.dev/docs/assertions.

## PR Checklist

- [x] PR has meaningful title
- [x] Summary describes changes
- [x] PR is ready to be merged
  - If not, use the arrow next to `Create Pull Request` to mark it as a draft. PR can be marked `Ready for review` when it's ready.
- [ ] Tests are added/update *(if required)*
- [ ] Documentation is updated/added *(if required)*

### CODE REVIEW

**Comment by fflaten** [comment]
@bravo-kernel Why doesn't this use `assertions/assertions` anymore? Special because it's named the same as the folder?

**Comment by bravo-kernel** [comment]
My best guess would be that this is some sort new Docusaurus behavior for same/same pages. IIRC people had been asking for that logic for some time and I must say, it feels logical to me. Anyway, should be easy to verify by creating `introduction/introduction` or sth. Can try this weekend unless you beat me to it.

**Comment by fflaten** [comment]
/azp run

```
Determining projects to restore...
  Restored D:\a\1\s\src\csharp\Pester\Pester.csproj (in 42.26 sec).
  Restored D:\a\1\s\src\csharp\PesterTests\PesterTests.csproj (in 2 min).
```
😠

**Comment by fflaten** [comment]
I see your point, but personal opinion is no. It breaks the natural reading flow (think about the next/previous page). A user needs to know the basics of `Should` before getting overwhelmed by all the assertions 🙂

**Pull request merged**
