### PR TITLE
Fix for issue #641

### PR DESCRIPTION
**Pull request by adbertram**

### CODE REVIEW

**Comment by adbertram** [comment]
How do I remove all of the changes that I did for my previous PR from this PR? Pretend you're talking to a Git newb here.... :)

**Comment by dlwyatt** [comment]
Make the changes in a different branch (starting from master)

**Comment by adbertram** [comment]
You are assuming a level of knowledge I do not possess at the moment. I
created a new branch, made the changes again and I still see all of my
previous commits.

**Comment by dlwyatt** [comment]
You must have been in your other branch when you created the new one. Do this:

Git checkout master
Git checkout -b SomeNewBranchName

**Comment by adbertram** [comment]
I keep creating a new branch and previous commits immediately show up with
git log.

**Pull request closed without merging**
