### PR TITLE
[V3Maintenance]Bump to v. 3.4.7 and add a deprecation messages

### PR DESCRIPTION
**Pull request by it-praktyk**

### CODE REVIEW

**Comment by it-praktyk** [comment]
Before this one please consider merging
- #764 
- #807

**Comment by it-praktyk** [comment]
@nohwnd is it any good reason to don't merge?

**Comment by nohwnd** [comment]
@it-praktyk the build script was not working till saturday, so I could not release this anyway. Gimme some time. This is very low priority.

**Comment by it-praktyk** [comment]
Is it any reason to don't merge it?

**Comment by nohwnd** [comment]
@it-praktyk Yes lack of time. I am not sure how to release it, and did not have time to look at this, yet.

**Pull request merged**
