### PR TITLE
Fix console warnings in Should-BeEquivalent.Tests.ps1

### PR DESCRIPTION
**Pull request by fflaten**
## PR Summary
Removes "Getting default equivalency options" warning spam in `tests.ps1` ouptut. Fixed by providing default options by... well, default in `Should-BeEquivalent.Tests.ps1`.

_Also replaces some calls to `New-Object`_

## PR Checklist

- [x] PR has meaningful title
- [x] Summary describes changes
- [x] PR is ready to be merged
  - If not, use the arrow next to `Create Pull Request` to mark it as a draft. PR can be marked `Ready for review` when it's ready.
- [x] Tests are added/update *(if required)*
- [ ] Documentation is updated/added *(if required)*

### CODE REVIEW

**Comment by nohwnd** [comment]
Clever. I would not think about doing it this way. Can the warning now be removed from the assertion and throw when the options are not provided?

**Comment by fflaten** [comment]
Yes

**Comment by nohwnd** [comment]
I won't, too many other things to fix before psconf :D

**Comment by fflaten** [comment]
Changed to only check if parameter was not provided (allows null). PSDefaultParameters-trick didn't work when `Compare-Equivalent`, even if I set the option for e.g. `Compare-DictionaryEquivalent`.

Didn't bother to troubleshooting further after title change issue #2477 🙂

**Pull request merged**
