### PR TITLE
Add header to Pester output that shows the version

### PR DESCRIPTION
**Pull request by KirkMunro**
## 1. General summary of the pull request

Fix issue #1342.

Told you I think ASCII art and most things retro are 😎 .

### CODE REVIEW

**Comment by renehernandez** [comment]
@KirkMunro It is failing to find the new HeaderMessage property in powershell 2

**Comment by KirkMunro** [comment]
FYI, the reason I did this as a new `HeaderMessage` string is because I thought that Gherkin and anything else that customizes the `StartMessage` wouldn't need to be changed as well (I assumed their string tables would only contain items that they wanted to change, not that they'd have to contain all strings. Turns out that was an incorrect assumption.

Maybe the header message, which does not contain anything that needs to be localized, should simply be defined inline without an entry in the string table at all. If you want that changed, let me know and I'll update it.

**Comment by nohwnd** [comment]
Looks good, and I also checked it visually in the output. Merging.

**Comment by Greg-Smulko** [comment]
@KirkMunro , the version number can be really useful, thanks for doing it. 

Just a quick question, I assume it's not possible as for now to disable the ASCII art logo? You know, I'm not against ASCII art overall, but in this case, it just pollutes our build log enormously...

**Comment by KirkMunro** [comment]
@Greg-Smulko There's no built-in support for that right now, no. The ASCII art isn't a requirement though. Seemed appropriate/fun at the time, but if it's just causing pollution and getting in the way of business, maybe we could either remove it altogether or have a switch to turn the logo off (i.e. -NoLogo, like PowerShell has). Thoughts @nohwnd?

**Comment by nohwnd** [comment]
@KirkMunro agree the logo was fun, but I saw way to many people complain about it. Let's revert that. :)

**Pull request merged**
