### PR TITLE
Introduce CompareObject matcher

### PR DESCRIPTION
**Pull request by dmalikov**
It would be nice to be able to do something like `@(2,1,3) | Should CompareObject @(1,2,3)`

### CODE REVIEW

**Comment by it-praktyk** [comment]
Guys,
please re-read what you wrote previously and take a decision.

If not I'll close this pull request after 14 days. Is it OK?

**Comment by nohwnd** [comment]
My older self was stupid and assertions that do too much suck. Comparing objects properly is way more difficult that what is implement in this PR so I would close this and rather work on my Assert module to get it object comparison to working state.

**Comment by it-praktyk** [comment]
@dmalikov, thank you for your contribution.

Based on opinion @nohwnd I'm closing your pull request now.

**Comment by nohwnd** [comment]
@dmalikov re-reading my answer I see it might be understood as arrogant, and downputting, but that was not my intention. It was supposed to have a jokeful tone to it. We had few bugs with Should Be doing weird things based on context, that is why I am trying to restrict assertions to do just one thing.  Also I tried implementing object comparison and it has 200+ tests and ton of code and I am still not done with it. :)

**Pull request closed without merging**
