### PR TITLE
Skip tests with global test suppression

### PR DESCRIPTION
**Pull request by claudiospizzi**
Implementation of the feature "Skip tests with global test suppression" #1048

### CODE REVIEW

**Comment by it-praktyk** [comment]
@ClaudioESSilva, can you review why tests failed under TeamCity-based CI?

**Comment by claudiospizzi** [comment]
@it-praktyk Found the issue, I've used the type [Ordered] which is not available in PS 2.0. Should be fixed now.

**Comment by nohwnd** [comment]
@claudiospizzi I know that closing a PR and implementing the same feature is a big no no, but I've set out to replace the internals of Pester with code that can do similar things and more. I tried to incorporate your PR into my code, but it uses a different approach so I unfortunately cannot use it, and I don't plan to merge this into Pester v4 either. 

I want to say thank you for your contribution, and thanks for the time that you've spent working on this. Hopefully I will be able to merge your next PR if there will be any. 🙂

**Comment by claudiospizzi** [comment]
Hi @nohwnd 

No problem, we still use my code in an internal fork. We will replace our fork, as soon as your update will meet our requirements. Maybe a hint to the changes, which PR do you reference?

**Comment by nohwnd** [comment]
@claudiospizzi there is no PR yet, I am developing it [here](https://github.com/nohwnd/Pester/tree/new-runtime)

**Pull request closed without merging**
