### PR TITLE
Fix an issue returning errors from Gherkin tests.

### PR DESCRIPTION
**Pull request by RandomNoun7**
In reference to Issue #904

### CODE REVIEW

**Comment by RandomNoun7** [comment]
Those changes were more comprehensive than I had in mind, but I don't have a problem with them.

**Comment by Jaykul** [comment]
@it-praktyk I believe your commit resolves the exception/ErrorRecord problem incorrectly. The whole problem is that the `$PesterException` variable frequently contains an `ErrorRecord` instead of an `Exception` -- if that's the case, you should pass it, not throw it away.

**Comment by it-praktyk** [comment]
The commit comment mentioned above is not part of any current pull request to Pester.

**Comment by Jaykul** [comment]
I have to say, I had forgotten all about this pull request (which I'd actually asked @RandomNoun7 to make, I think), and I included another fix for this bug in #931 when I saw the bug earlier today. (I was saying to myself: I was sure I had fixed this ... but since I didn't have a branch with the fix in it waiting to be pulled, I made one)...

@nohwnd @dlwyatt @it-praktyk who actually has merge permissions?

To whomever merges -- it would be good to merge this PR to give @RandomNoun7 credit. I'll be happy to rebase #931 to just do the `&$SafeCommands` stuff 😉

**Comment by it-praktyk** [comment]
> @nohwnd @dlwyatt @it-praktyk who actually has merge permissions?
Technically all of us. But based on a previous agreement I don't merge to master.

**Pull request closed without merging**
