### PR TITLE
Fix Gherkin for Linux (#937) and PS2

### PR DESCRIPTION
**Pull request by Jaykul**
Fix the linux case-sensitive problem causing #937

### CODE REVIEW

**Comment by Jaykul** [comment]
Incidentally, I didn't find a solution for testing PS2, and I don't see one on the CI server, so I'm not sure if we have any back-compat problems?

**Comment by dlwyatt** [comment]
V2 testing happens here: https://build.powershell.org/viewType.html?buildTypeId=Pester_TestPesterOnPowerShellV2

CI server is happily licensed again.

**Comment by it-praktyk** [comment]
I've tested PowerShell v.2 compatibility using Vagrant box made by @ferventcoder what you can download from https://app.vagrantup.com/ferventcoder/boxes/win2008r2-x64-nocm.

**Comment by it-praktyk** [comment]
@dlwyatt, currently to check build results login to the TeamCity server at https://build.powershell.org is needed. Is it by design?

**Comment by nohwnd** [comment]
@it-praktyk it aleays has been like that. Just click login as a guest.

**Comment by nohwnd** [comment]
@Jaykul It still fails on 8 errors. :/

**Comment by Jaykul** [comment]
The tests for Gherkin.Hook are legitimately failing just because the *tests* don't work in PS2

I had a look at those last night, rewrote them all -- the current tests are using reflection on the output of Get-Command and they say the "IsMandatory" property doesn't exist in PS2.  I just threw out the reflection and wrote some additional tests to validate the functionality instead. It was basically covered by other tests, but this way we'll capture exactly what's going on.

The other three failures are only failing intermittently, and I can't tell why from the logs. Hopefully they'll pass when I push this fix for the other tests, but either way, I will set up a VM to try to reproduce that failure. 

One possibility I can check (and/or put in a flag for) is the .NET Framework version -- the Gherkin assembly is compiled against .Net 3.5 (it's a *mandatory* upgrade for support, and was pre-installed on the only OSes left in support, as far as I know), but hypothetically you could be testing against something older.  Pester has never specified it's .NET Framework version -- I just made the assumption that we could require the OS be in support ;-)

**Comment by Jaykul** [comment]
I have to give up on this for now. I'll get back to it in 8 hours or so, after work.

The remaining failures appear to be because you made the tests use StrictMode in PS2. 
They pass in PS3+, including on Linux.

**Comment by Jaykul** [comment]
😅 😌 Huzzah! 🎉 🍾 🎆

**Comment by nohwnd** [comment]
@Jaykul I totally see someone will post a PR that will say `Clarify meaning of BAF in the code` :D 

And thanks, will release soon.

**Pull request merged**
