### PR TITLE
Fix Get-Help links

### PR DESCRIPTION
**Pull request by deejaygraham**
Comment based help in source has several .LINK problems. 

- URLs point to old pester wiki
- Several lines of commands under one .LINK entry leading to incorrect formatting
- Some commands are missing .LINK entries for their online version of help. 

See discussion https://github.com/pester/docs/issues/8

Not sure if this is finished. Unsure if each .LINK entry under a command should be to the online resource or left as plain text. Eg: 

.LINK 
Context

.LINK
https://pester.dev/docs/commands/Context

### CODE REVIEW

**Comment by nohwnd** [comment]
LGTM, waiting for it to build then I merge :)

**Comment by bravo-kernel** [comment]
## Do not merge yet

@deejaygraham I have re-generated the command reference using your PR changes in https://github.com/pester/docs/pull/25 so you can preview the results of your changes.

Preview: https://deploy-preview-25--pester-docs.netlify.com/

> I can easily re-generate so feel free to ask for a re-gen.

**Comment by bravo-kernel** [comment]
I vote for replacing all links with full URLs 👍

**Comment by deejaygraham** [comment]
I think full urls too. I made a mistake in including a self-reference to each topic so Describe has a link back to itself. 

Notice in the Describe page, first related .LINK is a full url which is shown in full. Other links are displayed better but are all linking back to the Describe page. E.g. It or Context !

**Comment by bravo-kernel** [comment]
Allright, this is interesting. Some background on why I think we should go for full URL only:

- we use PlatyPS to generate the initial markdown files for the command reference
- we then post-process (enrich) those markdowns so they become D2 usable
- PlatyPS uses a schema that matches Microsoft's specs, for LINK it is just a single line (IIRC)

We **could** choose to e.g. support markdown inside the LINK so it would look nice on the website but.. this would make the on-screen output confusing for the console Get-Help users IMO.

**Comment by nohwnd** [comment]
Okay, mention me when this should be merged.

**Comment by bravo-kernel** [comment]
@nohwnd ok on the "yes, we will use full URLs" ?

**Comment by nohwnd** [comment]
@bravo-kernel yes.

**Comment by bravo-kernel** [comment]
@deejaygraham the preview has been re-genned, looks sweet. Will you give the go/no-go on the merge?

**Comment by deejaygraham** [comment]
Yes, I'm happy for the merge to go ahead

**Pull request merged**
