### PR TITLE
Update Travis CI to run on both linux and macOS

### PR DESCRIPTION
**Pull request by GavinEke**
Add steps for Travis CI to run on both linux and osx

### CODE REVIEW

**Comment by it-praktyk** [comment]
Hmmm, interesting. 

1. https://travis-ci.org/pester/Pester/builds/295248991 - build time for macOS was shorter than expected
screenshot from 2017-10-31 12-31-13

2. condition to skip the failing test [added recently](https://github.com/pester/Pester/commit/d89db27f27b7db14f8635b837e9acad961ec13a0) didn't work

**Comment by it-praktyk** [comment]
@GavinEke, I've found a mistake in my exception - [missed brackets](https://github.com/pester/Pester/commit/93b286aea1655ee81f9f0c57793c8fbbc96de107) - please rebase your fork/branch. I hope that it will reinitiate CI.

**Comment by it-praktyk** [comment]
@GavinEke, BTW, thank you for your contribution.

**Comment by GavinEke** [comment]
Awesome thanks @it-praktyk

**Pull request merged**
