### PR TITLE
Edit README.md for clarity

### PR DESCRIPTION
**Pull request by timothywarner**
I adjusted some language, fixed some typos, and lightly tweaked the sample code.

### CODE REVIEW

**Comment by nohwnd** [comment]
Great thanks! 
Looks good to me. How about you @dlwyatt ?

**Comment by dlwyatt** [comment]
The only thing that jumps out at me is the change from Write-Host to Write-Output.  That's a functional change, not just adjusting language.  (It's probably still fine in the example, but I see no reason for it.)

**Comment by nohwnd** [comment]
Right. @timothywarner  could you please change the `write-output` back to the original `write-host`? Once you are done with the changes please review the changes by `git diff` and then  add the changes by`git add .`. Then you need to correct the previous commit by doing `git commit --amend --no-edit` (puts the current changes in the previous commit). Then you need to force push `git push --force` to your master so the changes are propagated to the PR as well.

**Comment by timothywarner** [comment]
Would you please patch it for me this time? I'm traveling all day. Thanks!

Incidentally, I changed Write-Host to Write-Output to conform to community practices.

**Comment by nohwnd** [comment]
Merged. 5dc122d481750cacc2e6c8e09491fbbf61faeb2e 

@timothywarner  Please don't post that Jeffrey Snover's article again :smile:

**Pull request closed without merging**
