### PR TITLE
Fix formatting to use automatic Struostrup style in VSCode

### LINKED ISSUE #1110: Code Formatting - Style Guide/Settings for VSCode
Yesterday I browsed through the pester code to understand it more deeply and help with issue #402, as it would help me to write simplified tests for a project I'm working on.
I'm working a lot with DSC Resources and am using VSCode to write my code. Many DSC projects use a vscode settings file (based on the [style guideline](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)) to ensure code formatting. It would be great to add this settings file for Pester too: [VSCode Settings for DSC Repoistories](https://github.com/PowerShell/DscResources/blob/master/DscResource.Template/.vscode/settings.json)

What's your opinion?

### PR DESCRIPTION
**Pull request by nohwnd**
Formatted all the files, and fixed tests that depend on formatting
- Checking that 2 calls to `Add-AssertonOperator` are the same (added whitespace made the scripts different)
- Checking fail position in file, adding whitespace moved the `$script` we use for check in a different line, so I've put it before the assertion with `;` so it stays on the same line.

Fix #1110

### CODE REVIEW

**Comment by fourpastmidnight** [comment]
Is this the same as OTBS that the PowerShell community seems to have adopted?

**Comment by nohwnd** [comment]
IDK what is the exact difference, but this one puts else on new line. And Pester is mentioned in the powershell style guide entry for this dtyle, so I figured why not.

**Comment by jkavanagh58** [comment]
Okay I can leverage these as ISE snippets just fine since they are XML so why the worry regarding VSCode OTBS?

**Comment by nohwnd** [comment]
@jkavanagh58 I don't get what you mean. Could you please re-phrase/expand on it?:)

**Comment by jkavanagh58** [comment]
> @jkavanagh58 I don't get what you mean. Could you please re-phrase/expand on it?:)

Sadly I don't remember now...

**Comment by nohwnd** [comment]
@jkavanagh58 we are not finding out then :D

**Comment by jkavanagh58** [comment]
Admittedly I am struggling to test this but I have some time on my hands so I will see if I can illustrate this better or maybe see where I need to "find target on wall, aim forehead and whack" 🔢 
Thanks

**Pull request merged**
