### PR TITLE
Fix Write-PesterStart to allow hashtables in $Path

### PR DESCRIPTION
**Pull request by JPRuskin**
Fix for:
 - Unexpected output when passing hashtable to Invoke-Pester #699
 - Bug in output where multiple Paths are passed in to -Scripts at Invoke-Pester #710

Changes:
 - Changes to the message generation from $Path in `Write-PesterStart`
 - Updated several ReportStrings within Output.ps1 to provide consistency when outputting multiple paths / tags / filters with the OFS setting.
 - Added tests for Write-PesterStart.

### CODE REVIEW

**Comment by JPRuskin** [comment]
Sure thing. Sorry about that.

**Comment by nohwnd** [comment]
Your changes fail the build on PowerShell v2 with:

```
[09:35:50][Step 1/1] PowerShell arguments: [-NoProfile, -NonInteractive, -ExecutionPolicy, ByPass, -File, C:\TeamCity\BuildAgent\temp\buildTmp\powershell3494319446830055004.ps1]
[09:36:26][Step 1/1] C:\TeamCity\BuildAgent\temp\buildTmp\powershell3494319446830055004.ps1 : Proper
[09:36:26][Step 1/1] ty 'Path' cannot be found on this object. Make sure that it exists.
[09:36:26][Step 1/1]     + CategoryInfo          : InvalidOperation: (.:OperatorToken) [Write-Error 
[09:36:26][Step 1/1]    ], RuntimeException
[09:36:26][Step 1/1]     + FullyQualifiedErrorId : PropertyNotFoundStrict,powershell349431944683005 
[09:36:26][Step 1/1]    5004.ps1
[09:36:26][Step 1/1]  
[09:36:26][Step 1/1] Process exited with code 1
[09:36:26][Step 1/1] Step Run Tests (Powershell) failed
```

**Comment by nohwnd** [comment]
@JPRuskin this PR is still not building, do you need help figuring something out?

**Comment by JPRuskin** [comment]
I hate to admit it, but I am a little stuck with the .\Functions\TestsRunningInCleanRunspace.Tests.ps1 tests on v2 and v3 (and, specifically, how my change has broken them). I'll take another look today and see if I can get it worked out.

**Comment by nohwnd** [comment]
@JPRuskin no worries I can try to fix that and push to your branch.

**Comment by nohwnd** [comment]
@JPRuskin Thank you for your work, but I had to close this without merging. :( I did try to fix it in your branch but the code was failing left and right for me, so I rather started fresh and fixed it in #816.

**Pull request closed without merging**
