### PR TITLE
Try Powershell Standard

### PR DESCRIPTION
**Pull request by JustinGrote**
## 1. General summary of the pull request
Adjusts build to only publish a .NET standard version of the module that works downlevel to PS3+ rather than separate net452 and netstandard2.0 builds

### CODE REVIEW

**Comment by nohwnd** [comment]
It did not work on the older versions right? netstandard2.0 is from net462, or rather net472, but powershell 3 is net451 (or 452 I don't remember). So the the reference assemblies target 3-5 and netstandards targets 6-7.

**Comment by JustinGrote** [comment]
@nohwnd It did work with PowershellStandard 3
https://github.com/PowerShell/PowerShellStandard

But I ran into a few edge cases that I decided I didn't want to mess with right now :)

**Comment by nohwnd** [comment]
Interesting. What were the edgecases?

**Comment by JustinGrote** [comment]
@nohwnd I don't recall specifically but some stuff didn't pass on PSv3 (it loaded though) and I didn't have time to spin up an old box with PSv3 on it to troubleshoot :)

**Pull request closed without merging**
